# Generated by Django 3.0.6 on 2020-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
